version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: grepp_development
      POSTGRES_USER: grepp
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grepp"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://grepp:password@db:5432/grepp_development
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "
        bundle install &&
        rails db:prepare &&
        rails db:seed &&
        rails server -b 0.0.0.0
      "

volumes:
  postgres_data:
  bundle_cache: