# PostgreSQL configuration for local development and testing
development:
  adapter: postgresql
  encoding: unicode
  database: grepp_development
  username: grepp
  password: password
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch("DB_NAME") { "grepp_test" } %>
  username: <%= ENV.fetch("DB_USER") { "grepp" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
