# PostgreSQL configuration for local development only
development:
  adapter: postgresql
  encoding: unicode
  database: grepp_development
  username: grepp
  password: password
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
